#!/usr/bin/env python

from scapy.all import *

ans, unans = srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst="192.168.30.0/24"),timeout=2,,verbose=0)

ans.summary(lambda (s,r): r.sprintf("Ethernet Address %Ether.src%  ARP Response Address %ARP.psrc%") )
