#! /usr/bin/env python

import sys
from scapy.all import *

ans,unans=sr(IP(dst=sys.argv[1])/TCP(sport=RandShort(),dport=(440,443),flags="S"),verbose=0)
#ans,unans=sr(IP(dst=sys.argv[1])/TCP(sport=RandShort(),dport=[80,440,443],flags="S"),verbose=0)

#ans.summary( lambda(s,r): r.sprintf("%TCP.sport% \t %TCP.flags%") )
ans.summary(lfilter = lambda (s,r): r.sprintf("%TCP.flags%") == "SA",prn=lambda(s,r):r.sprintf("%TCP.sport% is open"))



